node = 'PEC0-03615'
local_ip = "10.0.0.1"
application = "ziyan"
paths = ['./conf/conf.toml', './lua/enque_script.lua', './plugins/your_plugin.py']

[user_conf]
    [user_conf.check]
    # check config
    ip = '192.168.1.10' # cannet device host
    port = 4001 # cannet device port
    dbc_path = './conf/avl.dbc' # dbc file location
    
    # the frame_id you need to collect
    frame_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
    # the unnecessary messages key in frame
    signals = []


    [user_conf.handler]
    # handler config
     # 's' or 'u'
    unit = 'u'
        [user_conf.handler.exhaust]
        table_name = 'AVL_exhaust'
            [user_conf.handler.exhaust.tags]
            eqpt_no = 'PEC0-19001'
        
        [user_conf.handler.dyno]
        table_name = 'AVL_exhaust_dyno'
            [user_conf.handler.dyno.tags]
            eqpt_no = 'PEC0-19002'

[sender]
    lua_path = './lua/enque_script.lua'
    enque_log = true


[redis]
    db= 1
    host= 'localhost'
    port= 6379


[etcd]
    host = 'localhost'
#    host = '10.203.96.26'
    port = 2379

    # register status data to etcd server interval time (s)
    interval = 600


[web]
    set_name = 'status'
    order_status = 'get_status'


[log_configuration]
    console = true
    console_level = 'DEBUG'   #'DEBUG','INFO','WARNING','ERROR','CRITICAL'
    file = true
    file_level = 'DEBUG'  #'DEBUG','INFO','WARNING','ERROR','CRITICAL'
    remote = true
    remote_level = 'ERROR'  #'DEBUG','INFO','WARNING','ERROR','CRITICAL'
    log_file = 'logs/log.log'
    backup_count = 5
    max_size = 10240
    format_string = '(%(asctime)s), %(levelname)s, <%(threadName)s>, %(module)s, %(funcName)s, [%(lineno)d]: %(message)s'
